[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
nom = "7"
utility-belt = { git = "https://github.com/DataWraith/utility-belt.git", rev="cf2fa0a5e77" }
