[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
divan = "0.1"
winnow = "0.6"

[workspace.dependencies.utility-belt]
git = "https://github.com/DataWraith/utility-belt.git"
rev = "e3d6776f14a0"

