[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
divan = "0.1"
utility-belt = { git = "https://github.com/DataWraith/utility-belt.git", rev="c3d7eef3025c" }
winnow = "0.6"

