[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
divan = "0.1"
utility-belt = { git = "https://github.com/DataWraith/utility-belt.git", rev="99c6a733e1a5" }
winnow = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"


