[workspace]
members = [
    "day-*",
    "day-22",
    "day-23",
]
default-members = ["day-*"]
resolver = "2"

[workspace.dependencies]
divan = "0.1"

[workspace.dependencies.utility-belt]
git = "https://github.com/DataWraith/utility-belt.git"
rev = "554ed1027671"
