[workspace]
members = [
    "day-*",
    "day-08",
]
default-members = ["day-*"]
resolver = "2"

[workspace.dependencies]
divan = "0.1"

[workspace.dependencies.utility-belt]
git = "https://github.com/DataWraith/utility-belt.git"
rev = "a226316e3420"
